[package]
name = "r4300i-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modular-bitfield = "0.11.2"
num-traits = "0.2.18"
soft-aes = "0.2.2"
thiserror = "1.0.57"
